apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "gateway.fullname" . }}
data:
  gateway.gci: |-
    -resources-dir /opt/gateway/resources
    -setup /gateway/persist/setup/gateway.setup.xml
    {{- if .Values.demoMode }}
    -demo
    {{- else }}
    -gateway-name {{ tpl .Values.name . }}
    -licd-host {{ .Values.licenceDaemon.host | required "licenceDaemon.host is required" }}
    -licd-port {{ .Values.licenceDaemon.port | required "licenceDaemon.port is required" }}
    {{- if .Values.licenceDaemon.secure }}
    -licd-secure
    {{- end }}
    {{- end }}
    {{- if .Values.tls.enabled }}
    -ssl-certificate /secrets/tls.crt
    -ssl-certificate-key /secrets/tls.key
    {{- end }}
  gateway.setup.xml: |-
{{ and .Values.setup .Values.setup.file | default (include "gateway.defaultSetup" .) | indent 4 }}
