#!/usr/bin/python
import xml.etree.ElementTree as ET
import os

xmldoc = ET.parse(os.environ['_SETUP'])

def issue(s, p, m):
	return "<issue><severity>" +s+ "</severity><path>" +p+ "</path><message>" +m+ "</message></issue>"

print "<validation><issues>"
samplerIdx=0
for samplers in xmldoc.findall("./samplers"):
	for sampler in samplers.findall("./sampler"):
		samplerIdx = samplerIdx + 1
		for fkm in sampler.findall("./plugin/fkm"):
			usesPCRE = False
			spath = ""
			for node in fkm.findall("./isPCREMode/data"):
				if (node.text == "true"):
					usesPCRE = True
			if (usesPCRE == False):
				path = "/gateway/samplers/sampler[" + repr(samplerIdx) + "]"
				print issue("Error", path , "Middleware Requirements: FKM must use PCRE")
	


for httpConnectionRequirementsNode in xmldoc.findall("./operatingEnvironment/httpConnectionRequirements"):
	path = "/gateway/operatingEnvironment/httpConnectionRequirements"
	print issue("Critical", path , "Middleware Requirements:  Access to ORB pages is forbidden!!!!")


print "</issues></validation>"
