apiVersion: v1
kind: Service
metadata:
  name: {{ include "obcerv-app-grafana.fullname" . }}
  labels:
    {{- include "obcerv-app-grafana.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "obcerv-app-grafana.selectorLabels" . | nindent 4 }}
