# DNS name via which external clients will access the web console (required).
externalHostname: ""

docker:
  registry: docker.itrsgroup.com

ingress:
  enabled: true

  labels: { }
  path: /
  pathType: Prefix

  # Match a specific ingress controller.
  # ingressClassName: ""

  # HTTPS/TLS settings.
  tls:
    enabled: true

    # Optional name of secret containing the TLS certificate and key.
    # secretName: "my-tls-secret"

service:
  type: ClusterIP
  port: 8080
  annotations: { }

replicaCount: 1

image:
  repository: /obcerv/app/obcerv-app-webconsole
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets:
  - name: itrsdocker

nameOverride: ""
fullnameOverride: ""

podAnnotations: { }
podSecurityContext: { }
securityContext: { }
resources:
  requests:
    memory: "256Mi"
    cpu: "200m"
  limits:
    memory: "2048Mi"
    cpu: "1000m"
nodeSelector: { }
tolerations: [ ]
affinity: { }

internal:
  mesh:
    enabled: true
    annotations:
      linkerd.io/inject: enabled
      config.linkerd.io/proxy-cpu-request: "0.4"
      config.linkerd.io/proxy-cpu-limit: "1"
      config.linkerd.io/proxy-memory-request: 512Mi
      config.linkerd.io/proxy-memory-limit: 512Mi
  # Identity Access Management settings.
  iam:
    # Whether to require authentication.
    enabled: true

    scheme: http
    host: keycloak
    port: 8080
    realm: obcerv
    clientName: obcerv-apps
    disableTrustManager: true
    publicClient: false
    clientSecret: iam-apps-credentials

  # Port on which HTTP listens inside the pod.
  containerPort: 9999
  # Enable internal statsd export by default
  statsdEnabled: true

env:
  - name: INGESTION_CONFIG_PORT
    valueFrom:
      configMapKeyRef:
        name: instance-config
        key: ingestion.external-port
  - name: INGESTION_CONFIG_HOSTNAME
    valueFrom:
      configMapKeyRef:
        name: instance-config
        key: ingestion.external-hostname
  - name: OBCERV_CA_CRT
    valueFrom:
      secretKeyRef:
        name: obcerv-ca
        key: ca.crt
        optional: true