apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obcerv-app-centralised-config-daemon.fullname" . }}
data:
  config.yaml: |-
    monitoring:
      health-probe:
        listen-port: {{ .Values.healthProbePort | default 8080 }}

    grpc-servers:
      - port: {{ (.Values.daemon).port | default 50052 }}
        thread-pool-size: 1
        interceptors:
        {{- if (.Values.grpcCompression).enabled | default false }}
          - type: compression
        {{- end }}
          - type: error-handling
        {{- if (.Values.grpcLogging).enabled | default false }}
          - type: logging
            logResponses: {{ (.Values.grpcLogging).responses | default false }}
            {{- if (.Values.grpcLogging).include }}
            {{- with (.Values.grpcLogging).include }}
            included:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
            {{- if (.Values.grpcLogging).exclude }}
            {{- with (.Values.grpcLogging).exclude }}
            excluded:
            {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- end }}
        {{- end }}
    grpc-services:
      - type: centralised-config
        port: {{ (.Values.daemon).port | default 50052 }}
        maxGrpcCallDuration: {{ .Values.grpcTimeout | default "PT30S" }}
        gatewayValidationTimeout: {{ (.Values.daemon).gatewayValidationTimeout | default "PT30S" }}
        numValidatorThreads: {{ (.Values.daemon).numValidatorThreads | default 3 }}
        {{- if .Values.daemon.maxInboundGrpcMessageSizeBytes }}
        maxInboundGrpcMessageSizeBytes: {{ int .Values.daemon.maxInboundGrpcMessageSizeBytes }}
        {{- end }}
        {{- if (.Values.daemon).disableRecovery }}
        disableRecovery: (.Values.daemon).disableRecovery
        {{- end }}
        validationCacheExpiry:
          afterCreate: {{ ((.Values.daemon).validationCache).expireAfterCreate | default "PT1H" }}
          afterRead: {{ ((.Values.daemon).validationCache).expireAfterRead | default "PT5M" }}
      - type: gateway-artifacts
        port: {{ (.Values.daemon).port | default 50052 }}

    services:
      - type: permissions
        iam-service-name: {{ ((.Values.internal).iam).host | default "keycloak" }}
        iam-service-port: {{ ((.Values.internal).iam).port | default 8080 }}
        realm: {{ ((.Values.internal).iam).realm | default "obcerv" }}
        client-application-name: {{ ((.Values.internal).iam).clientName | default "obcerv-apps" }}
        public-key-cache-ttl-days: 1

      - type: platform-client-supplier
        services:
          - type: consensus-key-value-service
            hostname: kvstore.{{ .Release.Namespace }}.svc.cluster.local
            port: 7160

      - type: gateway-artifact-manager
        storagePath: {{ (.Values.daemon.persistence).mountPath | default "/gateways" }}
        pollInterval: {{ .Values.daemon.gatewayArchivesPollInterval | default "PT5S" }}

  logback.xml: |-
    <configuration>
      <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{"yyyy-MM-dd'T'HH:mm:ss.SSSXXX", UTC} [%thread] %-5level %logger - %msg%n</pattern>
        </encoder>
      </appender>

      <logger name="io.grpc" level="info"/>
      <logger name="io.netty" level="info"/>

      <root level="{{ .Values.daemon.logLevel | default "INFO" }}">
        <appender-ref ref="stdout"/>
      </root>
    </configuration>
