{{- if and (eq .Values.mode "Deployment") .Values.persistence.enabled (not .Values.agent.disableStorePersistence) .Values.routing.inbound.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "netprobe.fullname" . }}-agent-store
  labels:
    {{- include "netprobe.labels" . | nindent 4 }}
  annotations:
    # Prevent helm from deleting data when uninstalling the instance.
    helm.sh/resource-policy: "keep"
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.deploymentClaimSize }}
{{- end }}
