apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obcerv-app-signal-forecaster.fullname" . }}
data:
  config.yaml: |-
    monitoring:
      health-probe:
        listen-port: {{ .Values.healthProbePort }}

    services:
      - type: permissions
        iam-service-name: {{ .Values.internal.iam.host }}
        iam-service-port: {{ .Values.internal.iam.port }}
        realm: {{ .Values.internal.iam.realm }}
        client-application-name: {{ .Chart.Name }}
        public-key-cache-ttl-days: 1

      - type: platform-client-supplier
        services:
          - type: consensus-key-value-service
            hostname: kvstore.{{ .Release.Namespace }}.svc.cluster.local
            port: 7160
          - type: signal-service
            hostname: signals.{{ .Release.Namespace }}.svc.cluster.local
            port: 7161
          - type: metric-service
            hostname: metric-query.{{ .Release.Namespace }}.svc.cluster.local
            port: 7157

      - type: forecaster
        # The maximum number of buckets in a time series
        # A large maxBucket would mean a smaller bucket interval
        #
        # A max bucket of 2688 would mean a maximum of 1 hour interval
        # A max bucket of 672 would mean a maximum number of 1 hour interval
        maxBuckets: 336
        #
        # Timeout duration to publish a signal, set to 5 seconds by default if not provided.
        #
        signalPublishTimeoutDuration: PT5S
        #
        # Timeout duration to publish a signal, set to 5 minutes by default if not provided.
        #
        signalsBootstrapTimeoutDuration: PT5M

  logback.xml: |-
    <configuration>
      <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{"yyyy-MM-dd'T'HH:mm:ss.SSSXXX", UTC} [%thread] %-5level %logger - %msg%n</pattern>
        </encoder>
      </appender>

      <root level="{{ .Values.loglevel }}">
        <appender-ref ref="stdout"/>
      </root>
    </configuration>