# DNS name via which external clients will access the web console (required).
externalHostname: ""

docker:
  registry: docker.itrsgroup.com

ingress:
  enabled: true
  annotations: { }

  labels: { }
  path: /obcerv-app-api-gateway/
  pathType: Prefix

  # Match a specific ingress controller.
  # ingressClassName: ""

  # HTTPS/TLS settings.
  tls:
    enabled: true

    # Optional name of secret containing the TLS certificate and key.
    # secretName: "my-tls-secret"

service:
  type: ClusterIP
  port: 8080
  annotations: { }

replicaCount: 1

image:
  repository: /obcerv/app/obcerv-app-api-gateway
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart version.
  tag: ""

imagePullSecrets:
  - name: itrsdocker

nameOverride: ""
fullnameOverride: ""

podAnnotations: { }
podSecurityContext: { }
securityContext: { }
resources: { }
nodeSelector: { }
tolerations: [ ]
affinity: { }

internal:
  mesh:
    enabled: true
    annotations:
      linkerd.io/inject: enabled
      config.linkerd.io/proxy-cpu-request: "0.4"
      config.linkerd.io/proxy-cpu-limit: "1"
      config.linkerd.io/proxy-memory-request: 512Mi
      config.linkerd.io/proxy-memory-limit: 512Mi
  # Identity Access Management settings.
  iam:
    # Whether to require authentication.
    enabled: true

    scheme: http
    host: keycloak
    port: 8080
    realm: obcerv
    clientName: obcerv-apps
    disableTrustManager: true
    publicClient: false
    clientSecret: iam-apps-credentials

  # Port on which HTTP listens inside the pod.
  containerPort: 9999
  # Enable internal statsd export by default
  statsdEnabled: true

iam:
  image:
    repository: /obcerv/iam-tools
    tag: "1.0.0"
    pullPolicy: IfNotPresent