apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obcerv-app-capacity-planner-metrics.fullname" . }}
data:
  config.yaml: |-
    #  Metrics Daemon Config
    monitoring:
      reporting-interval: 10000
      health-probe:
        enabled: true
        listen-port: {{ .Values.healthProbePort | default 8080 }}

    services:
      - type: permissions
        iam-service-name: {{ ((.Values.internal).iam).host | default "keycloak" }}
        iam-service-port: {{ ((.Values.internal).iam).port | default 8080 }}
        realm: {{ ((.Values.internal).iam).realm | default "obcerv" }}
        client-application-name: {{ ((.Values.internal).iam).clientName | default "obcerv-apps" }}
        public-key-cache-ttl-days: 1

      - type: platform-client-supplier
        services:
          - type: consensus-key-value-service
            hostname: kvstore.{{ .Release.Namespace }}.svc.cluster.local
            port: 7160
          - type: metric-service
            hostname: metric-query.{{ .Release.Namespace }}.svc.cluster.local
            port: 7157
      - type: metrics-processor
        metrics-publisher-flags:
          initial-back-query-duration: {{ (.Values.metrics).initialBackQueryDuration | default "P7D" }}
          start-processing-check-frequency: {{ (.Values.metrics).startProcessingCheckFrequency | default "PT5M" }}
          max-metrics-start-processing: {{ (.Values.metrics).maxMetricsStartProcessing | default "1000" }}
          max-start-processing-duration: {{ (.Values.metrics).maxStartProcessingDuration | default "PT1H" }}
          query-length: {{ (.Values.metrics).queryLength | default "PT5M" }}
          catch-up-frequency: {{ (.Values.metrics).catchUpFrequency | default "PT1S" }}
          lag-length: {{ (.Values.metrics).lagLength | default "PT5M" }}
          force-back-query: {{ (.Values.metrics).forceBackQuery | default false }}
        http-client-settings:
          connection-timeout: {{ (.Values.httpClient).connectionTimeout | default "PT1M" }}
          read-timeout: {{ (.Values.httpClient).readTimeout | default "PT1M" }}
          write-timeout: {{ (.Values.httpClient).writeTimeout | default "PT1M" }}
          {{/*default does not work with boolean true see https://github.com/helm/helm/issues/3308*/}}
          {{- if eq "false" (((.Values.httpClient).compress) | toString) }}
          compress: false
          {{ else }}
          compress: true
          {{- end }}
          {{- if (.Values.httpClient).outputDirectory }}
          output-directory: {{ (.Values.httpClient).outputDirectory }}
          {{- end }}
        opsview-infra-metrics-settings:
          {{- if eq "false" (((.Values.opsviewInfra).enabled) | toString) }}
          enabled: false
          {{ else }}
          enabled: true
          {{- end }}
        geneos-infra-metrics-settings:
          {{- if eq "false" (((.Values.geneosInfra).enabled) | toString) }}
          enabled: false
          {{ else }}
          enabled: true
          {{- end }}

  logback.xml: |-
    <configuration>
      <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{"yyyy-MM-dd'T'HH:mm:ss.SSSXXX", UTC} [%thread] %-5level %logger - %msg%n</pattern>
        </encoder>
      </appender>

      <root level="{{ .Values.loglevel | default "INFO" }}">
        <appender-ref ref="stdout"/>
      </root>
    </configuration>