{{- $internal := .Values.internal | default dict -}}
{{- $mesh := $internal.mesh | default dict -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "obcerv-app-notifications-notifier.fullname" . }}
  labels:
  {{- include "obcerv-app-notifications-notifier.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "obcerv-app-notifications-notifier.selectorLabels" . | nindent 6 }}
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if $mesh.enabled }}
        {{- with $mesh.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- end }}
      labels:
    {{- include "obcerv-app-notifications-notifier.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- else }}
      imagePullSecrets:
      - name: itrsdocker
      {{- end }}
      containers:
      - name: {{ include "obcerv-app-notifications-notifier.fullname" . }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.docker.registry }}{{ .Values.notifier.image.repository }}:{{ .Values.notifier.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.notifier.image.pullPolicy | default "IfNotPresent" }}
        ports:
        - name: service
          containerPort: {{ (.Values.service).port | default 50052 }}
          protocol: TCP

        command:
        - java
        - -XX:+UseContainerSupport
        - -XX:InitialRAMPercentage=75
        - -XX:MaxRAMPercentage=75
        - -Dlogback.configurationFile=/app/config/logback.xml
        - -jar
        - /app/obcerv-app-notifications-notifier-daemon-{{ .Chart.AppVersion }}.jar
        - /app/config/config.yaml

        env:
        - name: IAM_CLIENT_ID
          value: {{ ((.Values.internal).iam).clientName | default "obcerv-apps" }}
        - name: IAM_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ ((.Values.internal).iam).clientSecret | default "iam-apps-credentials" }}
              key: client-secret
        - name: STATSD_SERVER
          valueFrom:
            fieldRef:
              {{- if(.Values.statsd).server }}
              fieldPath: {{ (.Values.statsd).server }}
              {{- else }}
              fieldPath: status.hostIP
              {{- end }}
        - name: STATSD_PROTOCOL
          value: "{{ (.Values.statsd).protocol | default "UDP" }}"
        - name: STATSD_PORT
          value: "{{ (.Values.statsd).port | default 8125 }}"
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CONTAINER
          value: {{ include "obcerv-app-notifications-notifier.fullname" . }}
        readinessProbe:
          httpGet:
            port: {{ .Values.healthProbePort | default 8080 }}
            path: /healthcheck
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6

        livenessProbe:
          httpGet:
            port: {{ .Values.healthProbePort | default 8080 }}
            path: /healthcheck
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 6

        resources:
            {{- if (.Values.notifier).resources }}
            {{- toYaml (.Values.notifier).resources | nindent 12 }}
            {{- else }}
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
          {{- end }}
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: {{ include "obcerv-app-notifications-notifier.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
