apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obcerv-app-centralised-config-rest-server.fullname" . }}
data:
  logback.xml: |-
    <configuration>
      <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{"yyyy-MM-dd'T'HH:mm:ss.SSSXXX", UTC} [%thread] %-5level %logger - %msg%n</pattern>
        </encoder>
      </appender>
      <root level="{{ .Values.restServer.logLevel | default "INFO" }}">
        <appender-ref ref="stdout"/>
      </root>
    </configuration>
