apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "obcerv-operator.fullname" . }}
  labels:
    {{- include "obcerv-operator.labels" . | nindent 4 }}
data:
  logback.xml: |-
    <configuration>
      <appender name="stdout" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger - %msg%n</pattern>
        </encoder>
      </appender>
      {{- range $k, $v := .Values.logging.loggers }}
      <logger name="{{ $k }}" level="{{ $v }}" />
      {{- end }}
      <root level="{{ .Values.logging.rootLevel }}">
        <appender-ref ref="stdout" />
      </root>
    </configuration>
